"""empty message

Revision ID: 707de79b45d6
Revises: a5cffa318ac2
Create Date: 2025-05-07 09:59:57.569191

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '707de79b45d6'
down_revision = 'a5cffa318ac2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pet',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('age', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('pet')
    # ### end Alembic commands ###
